:page_id: licensing
ifdef::env-github[]
****
link:https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-{page_id}.html[View this document on the Elastic website]
****
endif::[]
[id="{p}-{page_id}"]
= Manage licenses in ECK

When you install the default distribution of ECK, you receive a Basic license. Any Elastic stack application you manage through ECK will also be Basic licensed. Go to https://www.elastic.co/subscriptions to check which features are included in the Basic license for free.

IMPORTANT: ECK is only offered in two licensing tiers: Basic and Enterprise. Similar to the Elastic Stack, customers can download and use ECK with a Basic license for free. Basic license users can obtain support from GitHub or through our link:https://discuss.elastic.co[community]. A paid Enterprise subscription is required to engage the Elastic support team. For more details, check the link:https://www.elastic.co/subscriptions[Elastic subscriptions].

In this section, you are going to learn how to:

- <<{p}-start-trial>>
- <<{p}-add-license>>
- <<{p}-update-license>>
- <<{p}-get-usage-data>>


[float]
[id="{p}-start-trial"]
== Start a trial
If you want to try the features included in the Enterprise subscription, you can start a 30-day trial. To start a trial create a Kubernetes secret as shown below. Note that it must be in the same namespace as the operator:

[source,yaml]
----
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: eck-trial-license
  namespace: elastic-system
  labels:
    license.k8s.elastic.co/type: enterprise_trial
  annotations:
    elastic.co/eula: accepted <1>
EOF
----

<1> By setting this annotation to `accepted` you are expressing that you have accepted the Elastic EULA which can be found at https://www.elastic.co/eula.

NOTE: You can initiate a trial only if a trial has not been previously activated.

At the end of the trial period, the Platinum and Enterprise features operate in a link:https://www.elastic.co/guide/en/elastic-stack-overview/current/license-expiration.html[degraded mode]. You can revert to a Basic license, extend the trial, or purchase an Enterprise subscription.

[float]
[id="{p}-add-license"]
== Add a license
If you have a valid Enterprise subscription or a trial license extension, you will receive a license as a JSON file. The JSON file contains the cluster-level Enterprise licenses which enables ECK features, as well Platinum Stack licenses for recent and older Elasticsearch versions.

NOTE: After you install a license into ECK, all the Elastic Stack applications you manage with ECK have Platinum and Enterprise features enabled. Additionally, the link:https://www.elastic.co/guide/en/elasticsearch/reference/current/get-license.html[`_license`] API reports that individual Elasticsearch clusters are running under a Platinum license, and the command `kubectl -n elastic-system get configmap elastic-licensing -o yaml` returns a JSON document that, among other things, contains the current license level of the ECK operator. Applications created before you installed the license are upgraded to Platinum or Enterprise features without interruption of service after a short delay.

To add the license to your ECK installation, create a Kubernetes secret of the following form:

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  labels:
    license.k8s.elastic.co/scope: operator <1>
  name: eck-license
type: Opaque
data:
  license: "JSON license in base64 format"  <2>
----

<1> This label is required for ECK to identify your license secret.
<2> The license file can have any name.

You can easily create this secret using `kubectl` built-in support for secrets. Note that it must be in the same namespace as the operator:

[source,shell script]
----
kubectl create secret generic eck-license --from-file=my-license-file.json -n elastic-system
kubectl label secret eck-license "license.k8s.elastic.co/scope"=operator -n elastic-system
----

[float]
[id="{p}-update-license"]
== Update your license
Before your current Enterprise license expires, you will receive a new Enterprise license from Elastic (provided that your subscription is valid).

NOTE: You can check the expiry date of your license in the license file that you received from Elastic. Enterprise licenses are container licenses that include multiple licenses for individual Elasticsearch clusters with shorter expiry. Therefore, you will get a different expiry in Kibana or through the Elasticsearch link:https://www.elastic.co/guide/en/elasticsearch/reference/current/get-license.html[`_license`] API. ECK will automatically update the Elasticsearch cluster licenses until the expiry date of the ECK Enterprise license is reached.

To avoid any unintended downgrade of individual Elasticsearch clusters to a Basic license while installing the new license, we recommend to install the new Enterprise license as a new Kubernetes secret next to your existing Enterprise license. Just replace `eck-license` with a different name from the examples above. ECK will use the correct license automatically.

Once you have created the new license secret you can safely delete the old license secret.

[float]
[id="{p}-get-usage-data"]
== Get usage data
The operator periodically writes the total amount of Elastic resources under management to a configmap named `elastic-licensing`, which is in the same namespace as the operator. Here is an example of retrieving the data:

[source,shell]
----
> kubectl -n elastic-system get configmap elastic-licensing -o json | jq .data
{
  "eck_license_level": "enterprise",
  "eck_license_expiry_date": "2022-01-01T00:59:59+01:00",
  "enterprise_resource_units": "1",
  "max_enterprise_resource_units": "10",
  "timestamp": "2020-01-03T23:38:20Z",
  "total_managed_memory": "3.22GB"
}
----

If the operator metrics endpoint is enabled with the `--metrics-port` flag (check <<{p}-operator-config>>), license usage data will be included in the reported metrics. 

[source,shell]
----
> curl "$ECK_METRICS_ENDPOINT" | grep elastic_licensing
# HELP elastic_licensing_enterprise_resource_units_total Total enterprise resource units used
# TYPE elastic_licensing_enterprise_resource_units_total gauge
elastic_licensing_enterprise_resource_units_total{license_level="basic"} 6
# HELP elastic_licensing_memory_gigabytes_total Total memory used in GB
# TYPE elastic_licensing_memory_gigabytes_total gauge
elastic_licensing_memory_gigabytes_total{license_level="basic"} 357.01915648
----
