:page_id: upgrading-eck
ifdef::env-github[]
****
link:https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-{page_id}.html[View this document on the Elastic website]
****
endif::[]
[id="{p}-{page_id}"]
= Upgrade ECK

[id="{p}-ga-upgrade"]
== Upgrade to ECK 1.0.0 from previous versions

ECK 1.0.0 is largely compatible with the beta version of the operator (see <<{p}-ga-openshift,the exceptions for earlier Kubernetes and OpenShift versions>>). There is not a direct upgrade path from the alpha version.

To upgrade from 1.0.0-beta1, follow the <<{p}-quickstart>>. Note that all Elasticsearch and Kibana Pods go through a rolling restart when the operator is upgraded.

After the upgrade, use the `v1` API version for all Elastic manifests.

See the <<release-highlights-1.0.0>> for more information on new features.

[id="{p}-ga-openshift"]
== Upgrades in earlier Kubernetes and OpenShift versions

Upgrading from ECK 1.0.0-beta1 to 1.0.0 has some special considerations for users running either:
- Kubernetes versions < 1.13
- OpenShift 3.11

In this case, ECK must be uninstalled and reinstalled (due to link:https://github.com/kubernetes/kubernetes/issues/73752[an upstream bug] that was not backported). To uninstall ECK, see <<{p}-uninstalling-eck>>. Then you can follow the <<{p}-quickstart>> to install anew. You can save your existing `v1beta1` manifests, update them to the `v1` API version, <<{p}-snapshots,take snapshots>> and restore them as well.

After the upgrade, use the `v1` API version for all Elastic manifests.
