
- label: stack
  fixed:
    E2E_PROVIDER: gke
  mixed:
    - E2E_STACK_VERSION: "8.19.13"
    - E2E_STACK_VERSION: "9.2.7"
    # current stack version 9.3.2 is tested in all other tests no need to test it again
    - E2E_STACK_VERSION: "8.19.14-SNAPSHOT"
    - E2E_STACK_VERSION: "9.4.0-SNAPSHOT"

- label: ocp
  fixed:
    E2E_PROVIDER: ocp
  mixed:
    ## Test the current stack version.
    - E2E_STACK_VERSION: "9.3.2"
    ## Also test the next stack version to detect any change in the images that might not be compatible with the CRI-O runtime.
    - E2E_STACK_VERSION: "9.4.0-SNAPSHOT"

- label: kind
  fixed:
    E2E_PROVIDER: kind
  mixed:
    - DEPLOYER_KIND_NODE_IMAGE: kindest/node:v1.31.14@sha256:6f86cf509dbb42767b6e79debc3f2c32e4ee01386f0489b3b2be24b0a55aac2b
    - DEPLOYER_KIND_NODE_IMAGE: kindest/node:v1.32.11@sha256:5fc52d52a7b9574015299724bd68f183702956aa4a2116ae75a63cb574b35af8
    - DEPLOYER_KIND_NODE_IMAGE: kindest/node:v1.33.7@sha256:d26ef333bdb2cbe9862a0f7c3803ecc7b4303d8cea8e814b481b09949d353040
    - DEPLOYER_KIND_NODE_IMAGE: kindest/node:v1.34.3@sha256:08497ee19eace7b4b5348db5c6a1591d7752b164530a36f855cb0f2bdcbadd48
    # The latest version of kind/k8s needs to be listed twice at the end of this list
    # as it's tested in both ipv4 and ipv6 mode.
    - DEPLOYER_KIND_NODE_IMAGE: kindest/node:v1.35.0@sha256:452d707d4862f52530247495d180205e029056831160e22870e37e3f6c1ac31f
    - DEPLOYER_KIND_NODE_IMAGE: kindest/node:v1.35.0@sha256:452d707d4862f52530247495d180205e029056831160e22870e37e3f6c1ac31f
      DEPLOYER_KIND_IP_FAMILY: ipv6

- label: gke
  fixed:
    E2E_PROVIDER: gke

- label: gke-autopilot
  fixed:
    E2E_PROVIDER: gke-autopilot
    TESTS_MATCH: TestAutopilot

- label: resilience
  fixed:
    E2E_PROVIDER: gke
    E2E_DEPLOY_CHAOS_JOB: true

- label: eks-arm
  fixed:
    E2E_PROVIDER: eks-arm
    E2E_TEST_ENV_TAGS: arch:arm
    TEST_LICENSE: "" # disabled b/c https://github.com/elastic/elasticsearch/issues/68083
    MONITORING_SECRETS: "" # disabled b/c beats cannot run on ARM

- label: eks
  fixed:
    E2E_PROVIDER: eks

- label: aks
  fixed:
    E2E_PROVIDER: aks

# Stateless Elasticsearch tests
#- label: gke-stateless
#  fixed:
#    E2E_PROVIDER: gke
#    STATELESS: "true"
#
#- label: eks-stateless
#  fixed:
#    E2E_PROVIDER: eks
#    STATELESS: "true"
#
#- label: aks-stateless
#  fixed:
#    E2E_PROVIDER: aks
#    STATELESS: "true"
