# renovate: datasource=github-releases depName=golangci/golangci-lint
version: v2.13.0
name: golangci-lint-custom
destination: ./bin
plugins:
  - module: github.com/elastic/cloud-on-k8s/hack/linters/ssacrdlint
    import: github.com/elastic/cloud-on-k8s/hack/linters/ssacrdlint/plugin
    path: ./hack/linters/ssacrdlint
