# Build the operator binary
FROM docker.io/library/golang:1.20.5 as builder

ARG GO_LDFLAGS
ARG GO_TAGS
ARG LICENSE_PUBKEY_PATH

WORKDIR /go/src/github.com/elastic/cloud-on-k8s

# ENV KUBECTL_VERSION=1.26.3
# RUN curl -fsSLO https://dl.k8s.io/v${KUBECTL_VERSION}/bin/linux/$(uname -m | sed -e "s|x86_|amd|" -e "s|aarch|arm|")/kubectl && \
#     mv kubectl /usr/local/bin/kubectl && chmod +x /usr/local/bin/kubectl
ENV HELM_VERSION=3.10.1
RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && \
    chmod 700 get_helm.sh && ./get_helm.sh -v v${HELM_VERSION} --no-sudo && rm get_helm.sh

# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
COPY go.mod go.sum ./
RUN --mount=type=cache,mode=0755,target=/go/pkg/mod go mod download

# # Copy the sources
COPY pkg/ pkg/
COPY cmd cmd/

# Generate pkg/controller/common/license/zz_generated.pubkey.go and config/eck.yaml
ENV LICENSE_PUBKEY=/license.key
COPY ${LICENSE_PUBKEY_PATH} /license.key
COPY Makefile VERSION ./
# COPY .git .git
RUN make go-generate
# COPY config/ config/
# COPY deploy/ deploy/
# COPY hack/ hack/
# RUN make generate-crds-v1 generate-config-file
COPY deploy/ deploy/
RUN helm template deploy/eck-operator -s templates/configmap.yaml \
      -f deploy/eck-operator/values.yaml --set=webhook.enabled=false --set=telemetry.distributionChannel=image \
      > eck.yaml

# Build
RUN CGO_ENABLED=0 GOOS=linux \
      go build \
      -mod readonly \
      -ldflags "$GO_LDFLAGS" -tags="$GO_TAGS" -a \
      -o elastic-operator github.com/elastic/cloud-on-k8s/v2/cmd

# Copy the operator binary into a lighter image
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.8-860

# Update the base image packages to the latest versions
RUN microdnf update --setopt=tsflags=nodocs && microdnf clean all

ARG VERSION

# Add required ECK labels and override labels from base image
LABEL name="Elastic Cloud on Kubernetes" \
      io.k8s.display-name="Elastic Cloud on Kubernetes" \
      maintainer="eck@elastic.co" \
      vendor="Elastic" \
      version="$VERSION" \
      url="https://www.elastic.co/guide/en/cloud-on-k8s/" \
      summary="Run Elasticsearch, Kibana, APM Server, Enterprise Search, and Beats on Kubernetes and OpenShift" \
      description="Elastic Cloud on Kubernetes automates the deployment, provisioning, management, and orchestration of Elasticsearch, Kibana, APM Server, Beats, and Enterprise Search on Kubernetes" \
      io.k8s.description="Elastic Cloud on Kubernetes automates the deployment, provisioning, management, and orchestration of Elasticsearch, Kibana, APM Server, Beats, and Enterprise Search on Kubernetes"

COPY --from=builder /go/src/github.com/elastic/cloud-on-k8s/elastic-operator .
COPY config/eck.yaml /conf/eck.yaml

# Copy NOTICE.txt and LICENSE.txt into the image
COPY *.txt /licenses/

USER 1001

ENTRYPOINT ["./elastic-operator"]
CMD ["manager"]

