{{- if .Values.extraObjects }}
{{- if kindIs "slice" .Values.extraObjects }}
{{- range .Values.extraObjects }}
---
{{ tpl . $ }}
{{- end }}
{{- else if kindIs "map" .Values.extraObjects }}
{{- range $key, $val := .Values.extraObjects }}
---
{{ tpl $val $ }}
{{- end }}
{{- else }}
{{- fail (printf "extraObjects must be a list or map, got: %s" (kindOf .Values.extraObjects)) }}
{{- end }}
{{- end }}
