env:
  HELM_DRY_RUN: ${HELM_DRY_RUN:-true}
  HELM_FORCE: ${HELM_FORCE:-false}

steps:

  - label: ":go: helm releaser tool"
    key: "build-helm-releaser-tool"
    commands:
      - cd hack/helm/release
      - make build
      - buildkite-agent artifact upload bin/releaser
    agents:
      image: docker.elastic.co/ci-agent-images/cloud-k8s-operator/buildkite-agent:latest@sha256:5e1d1ba74e278d78b72eb6d908e58efe60011693dbb49595a6443e5a4bcecee8
      memory: "2G"

  - label: "operator dev helm chart"
    if: |
      ( build.branch == "main" && build.source != "schedule" )
      || build.tag != null
      || build.message =~ /^buildkite test .*release.*/
      || build.message == "release eck-operator dev helm charts"
      || build.message == "release eck-operator helm charts"
      || build.message == "release all helm charts"
    depends_on:
      - "build-helm-releaser-tool"
    key: "eck-operator-dev-helm"
    commands:
      - buildkite-agent artifact download "bin/releaser" /usr/local/
      - chmod u+x /usr/local/bin/releaser
      - releaser --env=dev --charts-dir=deploy/eck-operator --oci-charts-digests-file=eck-helm-dev-operator-oci-artifacts-digest.txt
      - buildkite-agent artifact upload eck-helm-dev-operator-oci-artifacts-digest.txt
    agents:
      image: docker.elastic.co/ci-agent-images/cloud-k8s-operator/buildkite-agent:latest@sha256:5e1d1ba74e278d78b72eb6d908e58efe60011693dbb49595a6443e5a4bcecee8
      memory: "2G"

  - label: "eck-stack dev helm charts"
    if: |
      ( build.branch == "main" && build.source != "schedule" )
      || build.tag != null
      || build.message =~ /^buildkite test .*release.*/
      || build.message == "release eck-stack dev helm charts"
      || build.message == "release eck-stack helm charts"
      || build.message == "release all helm charts"
    depends_on:
      - "eck-operator-dev-helm"
      - "build-helm-releaser-tool"
    key: "eck-stack-dev-helm"
    commands:
      - buildkite-agent artifact download "bin/releaser" /usr/local/
      - chmod u+x /usr/local/bin/releaser
      - releaser --env=dev --charts-dir=deploy/eck-stack --oci-charts-digests-file=eck-helm-dev-stack-oci-artifacts-digest.txt
      - buildkite-agent artifact upload eck-helm-dev-stack-oci-artifacts-digest.txt
    agents:
      image: docker.elastic.co/ci-agent-images/cloud-k8s-operator/buildkite-agent:latest@sha256:5e1d1ba74e278d78b72eb6d908e58efe60011693dbb49595a6443e5a4bcecee8
      memory: "2G"

  - label: "operator prod helm chart"
    if: |
      build.tag =~ /^v[0-9]+\.[0-9]+\.[0-9]+\$/
      || build.message == "release eck-operator helm charts"
      || build.message == "release all helm charts"
    depends_on:
      - "eck-stack-dev-helm"
      - "build-helm-releaser-tool"
    key: "eck-operator-prod-helm"
    commands:
      - buildkite-agent artifact download "bin/releaser" /usr/local/
      - chmod u+x /usr/local/bin/releaser
      - releaser --env=prod --charts-dir=deploy/eck-operator --oci-charts-digests-file=eck-helm-prod-operator-oci-artifacts-digest.txt
      - buildkite-agent artifact upload eck-helm-prod-operator-oci-artifacts-digest.txt
    agents:
      image: docker.elastic.co/ci-agent-images/cloud-k8s-operator/buildkite-agent:latest@sha256:5e1d1ba74e278d78b72eb6d908e58efe60011693dbb49595a6443e5a4bcecee8
      memory: "2G"

  - label: "eck-stack prod helm charts"
    if: |
      build.tag =~ /^v[0-9]+\.[0-9]+\.[0-9]+\$/
      || build.message == "release eck-stack helm charts"
      || build.message == "release all helm charts"
    depends_on:
      - "eck-operator-prod-helm"
      - "build-helm-releaser-tool"
    key: "eck-stack-prod-helm"
    commands:
      - buildkite-agent artifact download "bin/releaser" /usr/local/
      - chmod u+x /usr/local/bin/releaser
      - releaser --env=prod --charts-dir=deploy/eck-stack --oci-charts-digests-file=eck-helm-prod-stack-oci-artifacts-digest.txt
      - buildkite-agent artifact upload eck-helm-prod-stack-oci-artifacts-digest.txt
    agents:
      image: docker.elastic.co/ci-agent-images/cloud-k8s-operator/buildkite-agent:latest@sha256:5e1d1ba74e278d78b72eb6d908e58efe60011693dbb49595a6443e5a4bcecee8
      memory: "2G"
