[[release-highlights-2.13.0]]
== 2.13.0 release highlights

[float]
[id="{p}-2130-known-issues"]
=== Known issues
Upgrading Elasticsearch to version `8.14.0` from any version prior to `8.4.0` leads to Elasticsearch Pods not reaching a ready state. To avoid the issue, first upgrade to any version between `8.4.0` and up to and including `8.13.2` and then upgrade to `8.14.0`.

[float]
[id="{p}-2130-new-and-notable"]
=== New and notable

New and notable changes in version 2.13.0 of {n}. Check <<release-notes-2.13.0>> for the full list of changes.

[float]
[id="{p}-2130-eck-enterprise-search-helm-chart"]
=== ECK Enterprise Search Helm chart

ECK 2.13.0 supports managing Enterprise search resources via Helm charts, similarly to other components of the Elastic stack
(see https://github.com/elastic/cloud-on-k8s/tree/main/deploy/eck-stack/charts/eck-enterprise-search/examples[examples]).

[float]
[id="{p}-2130-allow-disabling-elastic-user"]
=== Allow disabling the elastic user

ECK 2.13.0 introduces a new option that allows a user to disable the elastic user from being created upon Elasticsearch creation. A use case for this would be when an organization/user would prefer to manage all users/roles via SSO (SAML/IDP/LDAP/etc)
(see https://github.com/elastic/cloud-on-k8s/blob/main/docs/orchestrating-elastic-stack-applications/security/users-and-roles.asciidoc#disabling-the-default-elastic-user[documentation]).

[float]
[id="{p}-2130-eck-logstash-ga"]
=== Logstash on ECK generally available

With ECK 2.13.0, support for Logstash is moving out of technical preview and is now generally available (GA). 
Logstash managed by ECK is now considered production-ready.

[float]
[id="{p}-2130-eck-logstash-licensing"]
=== Logstash licensing on ECK

ECK's resource https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-licensing.html#k8s-get-usage-data[management accounting] has been modified to include Logstash resources managed by ECK, which is provided for informational purposes. Billable consumption depends on license terms on a per customer basis (See https://www.elastic.co/agreements/global/self-managed[Self Managed Subscription Agreement]).

