[[release-highlights-1.6.0]]
== 1.6.0 release highlights

[float]
[id="{p}-160-new-and-notable"]
=== New and notable

New and notable changes in version 1.6.0 of {n}. Check <<release-notes-1.6.0>> for the full list of changes.

[float]
[id="{p}-160-ems-support"]
==== Support for Elastic Maps Server

In this release, ECK introduces the Elastic Maps Server CRD that allows you to run the link:https://www.elastic.co/guide/en/kibana/7.13/maps-connect-to-ems.html[Elastic Maps Service] in your Kubernetes environment. This is mostly relevant for air-gapped environments where Kibana server and browser clients are unable to reach the Elastic Maps Service for Maps rendering. 


[float]
[id="{p}-160-service-name-in-associations"]
==== Support for custom services in associations between components

When you create associations between components, for example using `elasticsearchRef`, you can now specify a custom service name to target specific nodes. For example, if you want to configure Kibana to target only Elasticsearch coordinating nodes, you can now reference a custom service by selecting only coordinating nodes.