[[release-highlights-1.3.1]]
== 1.3.1 release highlights

This is a patch release to address some issues found after the 1.3.0 release. See <<release-highlights-1.3.0>> for the full highlights of the 1.3.x series.



[float]
[id="{p}-131-fixes"]
=== Fixes

[float]
[id="{p}-131-workaround-kubernetes-bug"]
==== Workaround rare Kubernetes bug that could result in dataloss

When Secrets created and managed by ECK are copied to a different namespace, they are copied together with a reference to their owner. As the referenced resource is not present in this other namespace, a Kubernetes link:https://github.com/kubernetes/kubernetes/issues/65200[bug] causes garbage collector to remove resources previously referenced, which lead to deletion of all related resources, including PersistentVolumes. This bug is fixed in Kubernetes `1.20`, but as some ECK users might not be able to upgrade when it's released, we are providing the fix on ECK side. Secrets no longer have owner references. To avoid leaking Secrets when custom resources are added and removed, the operator itself is taking care of garbage collecting them.


[float]
[id="{p}-131-use-new-nodenames"]
==== Use new node_names query param for voting exclusions as of 7.8.0

When Elasticsearch master node was scheduled to be created, but, for any reason, didn't join the cluster, the operator was not able to remove it. New parameter introduced in Elasticsearch `7.8.0` allows the operator to make progress in those circumstances and with ECK `1.3.1` it will be used for any Elasticsearch version `7.8.0` and above.

