[[release-highlights-1.1.0]]
== 1.1.0 release highlights

[float]
[id="{p}-110-new-and-notable"]
=== New and notable

New and notable changes in version 1.1.0 of {n}. See <<release-notes-1.1.0>> for the full list of changes.

[float]
[id="{p}-110-remote-clusters"]
==== Remote cluster support

Establishing uni-directional connections from ECK-managed Elasticsearch clusters to other Elasticsearch clusters for link:https://www.elastic.co/guide/en/elasticsearch/reference/current/xpack-ccr.html[cross-cluster replication] and link:https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cross-cluster-search.html[cross-cluster search] purposes is now easy to achieve through a <<{p}-remote-clusters,few additions to the YAML manifest>>. This feature is available for all managed clusters running Elasticsearch 7.6 or higher with an Enterprise or Enterprise trial licence.


[float]
[id="{p}-110-declarative-user-management"]
==== Declarative user management

File realm users and roles are now <<{p}-users-and-roles,configurable using Kubernetes secrets>>. This enables consistent and auditable user management practices and GitOps use cases.


[float]
[id="{p}-110-enhanced-validation"]
==== Enhanced validation

Validation has been extended to more ECK resource types to catch invalid configurations during admission. Enabling the <<{p}-webhook,validating webhook>> will extend the capabilities of ECK to catch most common configuration issues during update operations as well.


[float]
[id="{p}-110-rbac"]
==== Enforce RBAC on associations

Access control policies can be enforced on cross-namespace Elasticsearch associations created by Kibana and APM Server instances. This feature is disabled by default to avoid breaking existing deployments. See <<{p}-restrict-cross-namespace-associations>> for more information.


[float]
[id="{p}-110-kibana-encryption-key"]
==== Stable Kibana encryption key

Unless the user has <<{p}-kibana-scaling,provided their own `xpack.security.encryptionKey`>>, the operator will generate a key that persists across restarts and upgrades. This prevents existing sessions from being invalidated due to a Kibana restart.


[float]
[id="{p}-110-beats-discovery"]
==== Filebeat discovery hints

ECK resources have the correct link:https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html[discovery hints] added by default to facilitate Filebeat discovery.


[float]
[id="{p}-110-container-registry"]
==== Default container registry for air-gapped installations

The default container registry used by the operator can be configured to ease deployments in air-gapped environments. When the <<{p}-container-registry-override,container registry is correctly configured>>, users no longer need to specify the container image field in their manifests.


[float]
[id="{p}-110-breaking-changes"]
=== Breaking changes

[float]
[id="{p}-110-breaking-roles"]
==== Removal of operator roles

The `--operator-roles` flag has been removed. The concept of `global` and `namespace` operator roles no longer exists. Instead, you can configure the operator to manage a pre-defined set of namespaces by passing a comma-separated list of namespaces to the `--namespaces` flag (default behaviour is to manage all namespaces). Instead of the `webhook` role, use the dedicated `--enable-webhook` flag to manage the webhook. See <<{p}-operator-config>> for more information about operator configuration flags.

[float]
[id="{p}-110-breaking-port-names"]
==== Container port name change

Container ports of managed resources are now named according to the protocol (`https` for TLS enabled ports and `http` for TLS disabled ports). Previously they were named `http` regardless of the protocol being used. If you have any configurations that refer to the container ports by name (Ingress configurations, for example), review those to ensure that they will continue to work after this change.
