[[release-highlights-1.9.0]]
== 1.9.0 release highlights

[float]
[id="{p}-190-new-and-notable"]
=== New and notable

New and notable changes in version 1.9.0 of {n}. Check <<release-notes-1.9.0>> for the full list of changes.

[float]
[id="{p}-190-tanzu-support"]
==== VMware Tanzu Kubernetes Grid support

ECK `1.9.0` introduces official support for link:https://tanzu.vmware.com/kubernetes-grid[VMware Tanzu Kubernetes Grid] starting with version `1.4`.

[float]
[id="{p}-190-suspend-pods"]
==== Pod suspension for Elasticsearch troubleshooting

Some debugging operations, like using the link:https://www.elastic.co/guide/en/elasticsearch/reference/current/node-tool.html[elasticsearch-node] tool, require access to the Pod before the Elasticsearch process starts. Starting with ECK `1.9.0`, this functionality is provided by the operator. Check the link:https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-troubleshooting-methods.html#k8s-suspend-elasticsearch[documentation] for more details.

[float]
[id="{p}-190-diag-tool"]
==== New and improved diagnostic tool

To provide more functionalities and better user experience we are moving away from script based diagnostic capture towards a dedicated binary. Check the ECK diagnostic tool link:https://github.com/elastic/eck-diagnostics[repository] for more details.

[float]
[id="{p}-190-elastic-license-v2"]
==== Elastic Cloud on Kubernetes moves to Elastic License v2
Following the Elastic Stack licensing changes in `7.11.0`, ECK `1.9.0` moves to Elastic License v2. For more details, check this link:https://www.elastic.co/blog/elastic-license-v2[blog post].

[float]
[id="{p}-190-known-issues"]
=== Known issues

- On Openshift versions 4.6 and below, when installing or upgrading to 1.9.[0,1], the operator will be stuck in a state of `Installing` within the Openshift UI, and found in a `CrashLoopBackoff` within Kubernetes because of Webhook certificate location mismatches. More information and work-around can be found in link:https://github.com/elastic/cloud-on-k8s/issues/5191[this issue].
- When using the `elasticsearchRef` mechanism with Elastic Agent in version 7.17 and later its Pods will enter a `CrashLoopBackoff`. The issue will be fixed in ECK 2.0 for Elasticsearch versions 8.0 and above. A workaround is described in link:https://github.com/elastic/cloud-on-k8s/issues/5323#issuecomment-1028954034[this issue].
