steps:

  # fail the build if e2e tests failures
  - label: "{{ .ShortFailuresCount }} failure(s)"
    command: exit {{ .ShortFailuresCount }}
    agents:
      image: docker.elastic.co/ci-agent-images/cloud-k8s-operator/buildkite-agent:latest@sha256:a72a7498c0a1d55276c0c9d3c518f5fc8fc0cca0fcf48a58c44f7599cb230afa
      memory: "2G"

  # notify e2e tests failures for the main branch and tags
  {{- if gt .ShortFailuresCount 0 }}
  - label: "notify"
    if: build.branch == "main" || build.tag != null
    command: echo "notify"
    agents:
      image: docker.elastic.co/ci-agent-images/cloud-k8s-operator/buildkite-agent:latest@sha256:a72a7498c0a1d55276c0c9d3c518f5fc8fc0cca0fcf48a58c44f7599cb230afa
      memory: "2G"

    notify:
      - slack:
          channels:
            - "#eck"
          message: |
          {{- range $i, $test := .ShortFailures }}
            🐞 `{{ $test.Name }}` {{ $test.EnvName }}
            {{- if gt $i $.MaxNotifiedShortFailures }}
              {{- break }}
            {{- end }}
          {{- end }}
          {{- if gt .ShortFailuresCount $.MaxNotifiedShortFailures }}
            Go to build to see all {{ .ShortFailuresCount }} failures.
          {{- end }}
  {{- end }}
