:page_id: stack-helm-chart
ifdef::env-github[]
****
link:https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-{page_id}.html[View this document on the Elastic website]
****
endif::[]
[id="{p}-{page_id}"]
= Elastic Stack Helm Chart

Starting from ECK 2.4.0, a Helm chart is available for managing Elastic Stack resources using the ECK Operator. It is available from the Elastic Helm repository and can be added to your Helm repository list by running the following command:

[source, sh]
----
helm repo add elastic https://helm.elastic.co
helm repo update
----

NOTE: The minimum supported version of Helm is 3.2.0.

[float]
[id="{p}-install-elasticsearch-kibana-helm"]
== Installing Elasticsearch and Kibana using the eck-stack Helm Chart

Similar to the <<{p}-deploy-elasticsearch,quickstart>>, the following section describes how to setup an Elasticsearch cluster with a simple Kibana instance managed by ECK, and how to customize a deployment using the eck-stack Helm chart's values.

[source,sh]
----
# Install an eck-managed Elasticsearch and Kibana using the default values, which deploys the quickstart examples.
helm install es-kb-quickstart elastic/eck-stack -n elastic-stack --create-namespace
----

[float]
[id="{p}-eck-stack-helm-customize"]
=== Customizing Kibana and Elasticsearch using the eck-stack Helm Chart's example values

There are example Helm values files for installing and managing a more advanced Elasticsearch and/or Kibana link:{eck_github}/tree/{eck_release_branch}/deploy/eck-stack/examples[in the project repository].

To use one or more of these example configurations, use the `--values` Helm option, as seen in the following section.

[source,sh,subs="attributes"]
----
# Install an eck-managed Elasticsearch and Kibana using the Elasticsearch node roles example with hot, warm, and cold data tiers, and the Kibana example customizing the http service.
helm install es-quickstart elastic/eck-stack -n elastic-stack --create-namespace \
    --values https://raw.githubusercontent.com/elastic/cloud-on-k8s/{eck_release_branch}/deploy/eck-stack/examples/elasticsearch/hot-warm-cold.yaml \
    --values https://raw.githubusercontent.com/elastic/cloud-on-k8s/{eck_release_branch}/deploy/eck-stack/examples/kibana/http-configuration.yaml
----

[float]
[id="{p}-install-fleet-agent-elasticsearch-kibana-helm"]
== Installing Fleet Server with Elastic Agents along with Elasticsearch and Kibana using the eck-stack Helm Chart

The following section builds upon the previous section, and allows installing Fleet Server, and Fleet-managed Elastic Agents along with Elasticsearch and Kibana.

[source,sh,subs="attributes"]
----
# Install an eck-managed Elasticsearch, Kibana, Fleet Server, and managed Elastic Agents using custom values.
helm install eck-stack-with-fleet elastic/eck-stack \
    --values https://raw.githubusercontent.com/elastic/cloud-on-k8s/{eck_release_branch}/deploy/eck-stack/examples/agent/fleet-agents.yaml -n elastic-stack
----

[float]
[id="{p}-install-logstash-elasticsearch-kibana-helm"]
== Installing Logstash along with Elasticsearch, Kibana and Beats using the eck-stack Helm Chart

The following section builds upon the previous sections, and allows installing Logstash along with Elasticsearch, Kibana and Beats.

[source,sh,subs="attributes"]
----
# Install an eck-managed Elasticsearch, Kibana, Beats and Logstash using custom values.
helm install eck-stack-with-logstash elastic/eck-stack \
    --values https://raw.githubusercontent.com/elastic/cloud-on-k8s/{eck_release_branch}/deploy/eck-stack/examples/logstash/basic-eck.yaml -n elastic-stack
----

[float]
[id="{p}-install-apm-server-elasticsearch-kibana-helm"]
== Installing a standalone Elastic APM Server along with Elasticsearch and Kibana using the eck-stack Helm Chart

The following section builds upon the previous sections, and allows installing a standalone Elastic APM Server along with Elasticsearch and Kibana.

[source,sh,subs="attributes"]
----
# Install an eck-managed Elasticsearch, Kibana, and standalone APM Server using custom values.
helm install eck-stack-with-apm-server elastic/eck-stack \
    --values https://raw.githubusercontent.com/elastic/cloud-on-k8s/{eck_release_branch}/deploy/eck-stack/examples/apm-server/basic.yaml -n elastic-stack
----

[float]
[id="{p}-install-enterprise-search-elasticsearch-kibana-helm"]
== Installing an Elastic Enterprise Search Server along with Elasticsearch and Kibana using the eck-stack Helm Chart

The following section builds upon the previous sections, and allows installing an Elastic Enterprise Search Server along with Elasticsearch and Kibana.

[source,sh,subs="attributes"]
----
# Install an eck-managed Elasticsearch, Kibana, and Enterprise Search Server using custom values.
helm install eck-stack-with-enterprise-search elastic/eck-stack \
    --values https://raw.githubusercontent.com/elastic/cloud-on-k8s/{eck_release_branch}/deploy/eck-stack/examples/enterprise-search/basic.yaml -n elastic-stack
----

[float]
[id="{p}-eck-stack-individual-components"]
=== Installing individual components of the Elastic Stack using the Helm Charts

You can install individual components in one of two ways using the provided Helm Charts.

1. Using Helm values
2. Using the individual Helm Charts directly

*Using Helm values to install only Elasticsearch*

[source,sh]
----
helm install es-quickstart elastic/eck-stack -n elastic-stack --create-namespace --set=eck-kibana.enabled=false
----

*Using the eck-elasticsearch Helm Chart directly to install only Elasticsearch* 

[source,sh]
----
helm install es-quickstart elastic/eck-elasticsearch -n elastic-stack --create-namespace
----
