:parent_page_id: elasticsearch-specification
:page_id: jvm-heap-size
ifdef::env-github[]
****
link:https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-{parent_page_id}.html#k8s-{page_id}[View this document on the Elastic website]
****
endif::[]
[id="{p}-{page_id}"]
= JVM heap size

Starting from version 7.11, Elasticsearch automatically sizes JVM heap based on a node’s roles and total memory. For more information, see link:{ref}/important-settings.html#heap-size-settings[Heap size settings].

These instructions apply if you are using:
- Versions of Elasticsearch before 7.11
- Elasticsearch 7.11 or later, and you want to override the default heap size. 

To manually change the heap size of Elasticsearch, set the `ES_JAVA_OPTS` environment variable in the `podTemplate`. Make sure you set the resource `requests` and `limits` at the same time so that the Pod gets enough resources allocated within the Kubernetes cluster. See <<{p}-compute-resources-elasticsearch>> for an example and more information.

IMPORTANT: For versions of Elasticsearch before 7.11, the default heap size is 1Gi.
