:parent_page_id: elasticsearch-specification
:page_id: jvm-heap-size
ifdef::env-github[]
****
link:https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-{parent_page_id}.html#k8s-{page_id}[View this document on the Elastic website]
****
endif::[]
[id="{p}-{page_id}"]
= JVM heap size

These instructions apply if you are using:
- Versions of Elasticsearch before 7.11
- Elasticsearch 7.11 or later, and you want to change the default heap size. 

To change the heap size of Elasticsearch, set the `ES_JAVA_OPTS` environment variable in the `podTemplate`. It is also highly recommended to set the resource `requests` and `limits` at the same time to ensure that the Pod gets enough resources allocated within the Kubernetes cluster. See <<{p}-compute-resources-elasticsearch>> for an example and more information.

IMPORTANT: For versions of Elasticsearch before 7.11, the default heap size is of 1Gi.

For more information, see the entry for `heap size` in the link:{ref}/important-settings.html[Important Elasticsearch configuration] documentation.