//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License 2.0;
// you may not use this file except in compliance with the Elastic License 2.0.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicy) DeepCopyInto(out *AutoscalingPolicy) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Deciders != nil {
		in, out := &in.Deciders, &out.Deciders
		*out = make(map[string]DeciderSettings, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(DeciderSettings, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicy.
func (in *AutoscalingPolicy) DeepCopy() *AutoscalingPolicy {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicySpec) DeepCopyInto(out *AutoscalingPolicySpec) {
	*out = *in
	in.NamedAutoscalingPolicy.DeepCopyInto(&out.NamedAutoscalingPolicy)
	in.AutoscalingResources.DeepCopyInto(&out.AutoscalingResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicySpec.
func (in *AutoscalingPolicySpec) DeepCopy() *AutoscalingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in AutoscalingPolicySpecs) DeepCopyInto(out *AutoscalingPolicySpecs) {
	{
		in := &in
		*out = make(AutoscalingPolicySpecs, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicySpecs.
func (in AutoscalingPolicySpecs) DeepCopy() AutoscalingPolicySpecs {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicySpecs)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicyStatus) DeepCopyInto(out *AutoscalingPolicyStatus) {
	*out = *in
	if in.NodeSetNodeCount != nil {
		in, out := &in.NodeSetNodeCount, &out.NodeSetNodeCount
		*out = make(NodeSetNodeCountList, len(*in))
		copy(*out, *in)
	}
	in.ResourcesSpecification.DeepCopyInto(&out.ResourcesSpecification)
	if in.PolicyStates != nil {
		in, out := &in.PolicyStates, &out.PolicyStates
		*out = make([]PolicyState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastModificationTime.DeepCopyInto(&out.LastModificationTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicyStatus.
func (in *AutoscalingPolicyStatus) DeepCopy() *AutoscalingPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingResources) DeepCopyInto(out *AutoscalingResources) {
	*out = *in
	if in.CPURange != nil {
		in, out := &in.CPURange, &out.CPURange
		*out = new(QuantityRange)
		(*in).DeepCopyInto(*out)
	}
	if in.MemoryRange != nil {
		in, out := &in.MemoryRange, &out.MemoryRange
		*out = new(QuantityRange)
		(*in).DeepCopyInto(*out)
	}
	if in.StorageRange != nil {
		in, out := &in.StorageRange, &out.StorageRange
		*out = new(QuantityRange)
		(*in).DeepCopyInto(*out)
	}
	out.NodeCountRange = in.NodeCountRange
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingResources.
func (in *AutoscalingResources) DeepCopy() *AutoscalingResources {
	if in == nil {
		return nil
	}
	out := new(AutoscalingResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Conditions) DeepCopyInto(out *Conditions) {
	{
		in := &in
		*out = make(Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Conditions.
func (in Conditions) DeepCopy() Conditions {
	if in == nil {
		return nil
	}
	out := new(Conditions)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CountRange) DeepCopyInto(out *CountRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CountRange.
func (in *CountRange) DeepCopy() *CountRange {
	if in == nil {
		return nil
	}
	out := new(CountRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchAutoscalerStatus) DeepCopyInto(out *ElasticsearchAutoscalerStatus) {
	*out = *in
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AutoscalingPolicyStatuses != nil {
		in, out := &in.AutoscalingPolicyStatuses, &out.AutoscalingPolicyStatuses
		*out = make([]AutoscalingPolicyStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchAutoscalerStatus.
func (in *ElasticsearchAutoscalerStatus) DeepCopy() *ElasticsearchAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedAutoscalingPolicy) DeepCopyInto(out *NamedAutoscalingPolicy) {
	*out = *in
	in.AutoscalingPolicy.DeepCopyInto(&out.AutoscalingPolicy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedAutoscalingPolicy.
func (in *NamedAutoscalingPolicy) DeepCopy() *NamedAutoscalingPolicy {
	if in == nil {
		return nil
	}
	out := new(NamedAutoscalingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResources) DeepCopyInto(out *NodeResources) {
	*out = *in
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResources.
func (in *NodeResources) DeepCopy() *NodeResources {
	if in == nil {
		return nil
	}
	out := new(NodeResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResourcesInt64) DeepCopyInto(out *NodeResourcesInt64) {
	*out = *in
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(ResourceListInt64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(ResourceListInt64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResourcesInt64.
func (in *NodeResourcesInt64) DeepCopy() *NodeResourcesInt64 {
	if in == nil {
		return nil
	}
	out := new(NodeResourcesInt64)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSetNodeCount) DeepCopyInto(out *NodeSetNodeCount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSetNodeCount.
func (in *NodeSetNodeCount) DeepCopy() *NodeSetNodeCount {
	if in == nil {
		return nil
	}
	out := new(NodeSetNodeCount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in NodeSetNodeCountList) DeepCopyInto(out *NodeSetNodeCountList) {
	{
		in := &in
		*out = make(NodeSetNodeCountList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSetNodeCountList.
func (in NodeSetNodeCountList) DeepCopy() NodeSetNodeCountList {
	if in == nil {
		return nil
	}
	out := new(NodeSetNodeCountList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyState) DeepCopyInto(out *PolicyState) {
	*out = *in
	if in.Messages != nil {
		in, out := &in.Messages, &out.Messages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyState.
func (in *PolicyState) DeepCopy() *PolicyState {
	if in == nil {
		return nil
	}
	out := new(PolicyState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantityRange) DeepCopyInto(out *QuantityRange) {
	*out = *in
	out.Min = in.Min.DeepCopy()
	out.Max = in.Max.DeepCopy()
	if in.RequestsToLimitsRatio != nil {
		in, out := &in.RequestsToLimitsRatio, &out.RequestsToLimitsRatio
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantityRange.
func (in *QuantityRange) DeepCopy() *QuantityRange {
	if in == nil {
		return nil
	}
	out := new(QuantityRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ResourceListInt64) DeepCopyInto(out *ResourceListInt64) {
	{
		in := &in
		*out = make(ResourceListInt64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceListInt64.
func (in ResourceListInt64) DeepCopy() ResourceListInt64 {
	if in == nil {
		return nil
	}
	out := new(ResourceListInt64)
	in.DeepCopyInto(out)
	return *out
}
