// +build !ignore_autogenerated

// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaElasticsearchAssociation) DeepCopyInto(out *KibanaElasticsearchAssociation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaElasticsearchAssociation.
func (in *KibanaElasticsearchAssociation) DeepCopy() *KibanaElasticsearchAssociation {
	if in == nil {
		return nil
	}
	out := new(KibanaElasticsearchAssociation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KibanaElasticsearchAssociation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaElasticsearchAssociationList) DeepCopyInto(out *KibanaElasticsearchAssociationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KibanaElasticsearchAssociation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaElasticsearchAssociationList.
func (in *KibanaElasticsearchAssociationList) DeepCopy() *KibanaElasticsearchAssociationList {
	if in == nil {
		return nil
	}
	out := new(KibanaElasticsearchAssociationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KibanaElasticsearchAssociationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaElasticsearchAssociationSpec) DeepCopyInto(out *KibanaElasticsearchAssociationSpec) {
	*out = *in
	out.Elasticsearch = in.Elasticsearch
	out.Kibana = in.Kibana
	out.Monitoring = in.Monitoring
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaElasticsearchAssociationSpec.
func (in *KibanaElasticsearchAssociationSpec) DeepCopy() *KibanaElasticsearchAssociationSpec {
	if in == nil {
		return nil
	}
	out := new(KibanaElasticsearchAssociationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaElasticsearchAssociationStatus) DeepCopyInto(out *KibanaElasticsearchAssociationStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaElasticsearchAssociationStatus.
func (in *KibanaElasticsearchAssociationStatus) DeepCopy() *KibanaElasticsearchAssociationStatus {
	if in == nil {
		return nil
	}
	out := new(KibanaElasticsearchAssociationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectSelector) DeepCopyInto(out *ObjectSelector) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectSelector.
func (in *ObjectSelector) DeepCopy() *ObjectSelector {
	if in == nil {
		return nil
	}
	out := new(ObjectSelector)
	in.DeepCopyInto(out)
	return out
}
