// +build !ignore_autogenerated

// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApmServerElasticsearchAssociation) DeepCopyInto(out *ApmServerElasticsearchAssociation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApmServerElasticsearchAssociation.
func (in *ApmServerElasticsearchAssociation) DeepCopy() *ApmServerElasticsearchAssociation {
	if in == nil {
		return nil
	}
	out := new(ApmServerElasticsearchAssociation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApmServerElasticsearchAssociation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApmServerElasticsearchAssociationList) DeepCopyInto(out *ApmServerElasticsearchAssociationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApmServerElasticsearchAssociation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApmServerElasticsearchAssociationList.
func (in *ApmServerElasticsearchAssociationList) DeepCopy() *ApmServerElasticsearchAssociationList {
	if in == nil {
		return nil
	}
	out := new(ApmServerElasticsearchAssociationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApmServerElasticsearchAssociationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApmServerElasticsearchAssociationSpec) DeepCopyInto(out *ApmServerElasticsearchAssociationSpec) {
	*out = *in
	out.Elasticsearch = in.Elasticsearch
	out.ApmServer = in.ApmServer
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApmServerElasticsearchAssociationSpec.
func (in *ApmServerElasticsearchAssociationSpec) DeepCopy() *ApmServerElasticsearchAssociationSpec {
	if in == nil {
		return nil
	}
	out := new(ApmServerElasticsearchAssociationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApmServerElasticsearchAssociationStatus) DeepCopyInto(out *ApmServerElasticsearchAssociationStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApmServerElasticsearchAssociationStatus.
func (in *ApmServerElasticsearchAssociationStatus) DeepCopy() *ApmServerElasticsearchAssociationStatus {
	if in == nil {
		return nil
	}
	out := new(ApmServerElasticsearchAssociationStatus)
	in.DeepCopyInto(out)
	return out
}
