# Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
# or more contributor license agreements. Licensed under the Elastic License 2.0;
# you may not use this file except in compliance with the Elastic License 2.0.

steps:

{{- range $test := .Tests }}

  # self-contained suite: create k8s cluster, run e2e tests, delete k8s cluster
  - group: "{{ $test.Name }}"
    steps:

    {{- if $test.RemoteKubeconfig }}

      # create k8s cluster
      - label: ":k8s: create cluster {{ $test.Name }}"
        key: "e2e-cluster-{{ $test.SlugName }}"

        # allow re-running from the UI even after it passed
        retry:
          manual:
            permit_on_passed: true

        env:
          {{- range $key, $val := $test.Env }}
          {{$key}}: "{{$val}}"
          {{- end }}

        commands:
          - .buildkite/scripts/test/set-deployer-config.sh
          {{- if $test.Dind }}
          - make -C .buildkite TARGET="run-deployer" ci
          {{- else }}
          - make run-deployer
          {{- end }}

        agents:
          {{- if $test.Dind }}
          provider: "gcp"
          image: "family/core-ubuntu-2204"
          {{- if or (eq $test.Provider "kind") (eq $test.Provider "k3d") }}
          machineType: "{{ $.K8sInDockerMachineType }}"
          {{- end }}
          {{- else }}
          image: docker.elastic.co/ci-agent-images/cloud-k8s-operator/buildkite-agent:latest@sha256:1faa746580da83750c129c62f1a7a9e1c7ebccb5526f4bbf4bcd0fc05a997699
          memory: "5G"
          {{- end }}

    {{- end }}

      # create k8s cluster and run e2e tests, or just run e2e tests (if RemoteKubeconfig)
      {{- if $test.RemoteKubeconfig }}
      - label: ":go: run e2e tests {{ $test.Name }}"
      {{- else }}
      - label: ":k8s: :go: run e2e tests {{ $test.Name }}"
      {{- end }}
        key: "e2e-{{ $test.SlugName }}"

        # allow re-running from the UI even after it passed
        retry:
          manual:
            permit_on_passed: true

        {{- if $test.RemoteKubeconfig }}
        depends_on:
          - "e2e-cluster-{{ $test.SlugName }}"
          # let's be optimistic and run the tests without dependency on the images build
        {{- end }}

        env:
          {{- range $key, $val := $test.Env }}
          {{$key}}: "{{$val}}"
          {{- end }}

        commands:
          {{- range $key, $val := $test.Env }}
          - echo "{{$key}}={{$val}}" >> .env
          {{- end }}

          - .buildkite/scripts/test/set-deployer-config.sh

          {{- $deployerCommand := "run-deployer" }}
          {{- if $test.RemoteKubeconfig }}
            {{- $deployerCommand = "set-kubeconfig" }}
          {{- end }}

          {{- if $test.Dind }}
          - make -C .buildkite TARGET="{{ $deployerCommand }} e2e-run" ci
          {{- else }}
          - make {{ $deployerCommand }} e2e-run
          {{- end }}

        agents:
          {{- if $test.Dind }}
          provider: "gcp"
          image: "family/core-ubuntu-2204"
          {{- if or (eq $test.Provider "kind") (eq $test.Provider "k3d") }}
          machineType: "{{ $.K8sInDockerMachineType }}"
          diskSizeGb: 200
          {{- end }}
          {{- else }}
          image: docker.elastic.co/ci-agent-images/cloud-k8s-operator/buildkite-agent:latest@sha256:1faa746580da83750c129c62f1a7a9e1c7ebccb5526f4bbf4bcd0fc05a997699
          memory: "4G"
          {{- end }}

        artifact_paths:
          - e2e-tests-*.json
          - "eck-diagnostic*.zip"

    {{- if $test.Cleanup }}

      # delete k8s cluster
      - label: ":broom: cleanup {{ $test.Name }}"
        depends_on:
          - step: "e2e-{{ $test.SlugName }}"
            allow_failure: true
        env:
          {{- range $key, $val := $test.Env }}
          {{$key}}: "{{$val}}"
          {{- end }}
          DEPLOYER_OPERATION: delete
        soft_fail: true
        # allow re-running from the UI even after it passed
        retry:
          manual:
            permit_on_passed: true
        commands:
          - .buildkite/scripts/test/set-deployer-config.sh
        {{- if not $test.Dind }}
          - make run-deployer
        agents:
          image: docker.elastic.co/ci-agent-images/cloud-k8s-operator/buildkite-agent:latest@sha256:1faa746580da83750c129c62f1a7a9e1c7ebccb5526f4bbf4bcd0fc05a997699
          memory: "4G"
        {{- else }}
          - make -C .buildkite TARGET="run-deployer" ci
        agents:
          provider: "gcp"
          image: "family/core-ubuntu-2204"
        {{- end }}

    {{- end }}

{{- end }}

  - label: "aggregate tests-results"
    depends_on:
      {{- range $test := .Tests }}
      - step: "e2e-{{ $test.SlugName }}"
        allow_failure: true
      {{- end }}
    # allow recalculating the results after retrying one or more suites
    retry:
      manual:
        permit_on_passed: true
    command: .buildkite/scripts/test/report-tests-results.sh
    artifact_paths:
      - ".buildkite/e2e/reporter/*.md"
      - ".buildkite/e2e/reporter/*.yml"
    agents:
      image: docker.elastic.co/ci-agent-images/cloud-k8s-operator/buildkite-agent:latest@sha256:1faa746580da83750c129c62f1a7a9e1c7ebccb5526f4bbf4bcd0fc05a997699
      memory: "2G"
