{{- if $.Values.eck_agent.enabled -}}
{{- include "elasticagent.daemonset" $ -}}
{{- if $.Values.eck_agent.daemonset.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: eck-agent-daemonset
  namespace: {{ .namespace | default $.Release.Namespace | quote }}
  labels:
    {{- include "elasticagent.labels" $ | nindent 4 }}
  annotations:
    {{- with .Values.eck_agent.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
stringData:
  agent.yml: |-
    id: eck-agent-daemonset
    secret_references: []
    agent:
      monitoring:
        namespace: {{ .Values.kubernetes.namespace }}
        use_output: default
        enabled: true
        logs: true
        metrics: true
    providers:
      kubernetes_leaderelection:
        enabled: false
      kubernetes:
        node: ${NODE_NAME}
        scope: node
        hints:
          {{ .Values.kubernetes.hints | toYaml }}
        kubernetes_secrets:
          enabled: true
    inputs:
    {{- range $configName := $.Values.eck_agent.daemonset.enabled_configs }}
    {{- include (print $configName ".input") $ | nindent 6 }}
    {{- end}}
{{- end -}}
{{- end -}}