//go:build !ignore_autogenerated

// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License 2.0;
// you may not use this file except in compliance with the Elastic License 2.0.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudConnectedMode) DeepCopyInto(out *CloudConnectedMode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudConnectedMode.
func (in *CloudConnectedMode) DeepCopy() *CloudConnectedMode {
	if in == nil {
		return nil
	}
	out := new(CloudConnectedMode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudConnectedMode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudConnectedModeList) DeepCopyInto(out *CloudConnectedModeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudConnectedMode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudConnectedModeList.
func (in *CloudConnectedModeList) DeepCopy() *CloudConnectedModeList {
	if in == nil {
		return nil
	}
	out := new(CloudConnectedModeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudConnectedModeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudConnectedModeSpec) DeepCopyInto(out *CloudConnectedModeSpec) {
	*out = *in
	in.ResourceSelector.DeepCopyInto(&out.ResourceSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudConnectedModeSpec.
func (in *CloudConnectedModeSpec) DeepCopy() *CloudConnectedModeSpec {
	if in == nil {
		return nil
	}
	out := new(CloudConnectedModeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudConnectedModeStatus) DeepCopyInto(out *CloudConnectedModeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudConnectedModeStatus.
func (in *CloudConnectedModeStatus) DeepCopy() *CloudConnectedModeStatus {
	if in == nil {
		return nil
	}
	out := new(CloudConnectedModeStatus)
	in.DeepCopyInto(out)
	return out
}
