:page_id: take-eck-dump
ifdef::env-github[]
****
link:https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-{page_id}.html[View this document on the Elastic website]
****
endif::[]
[id="{p}-{page_id}"]
= Run eck-diagnostics

`eck-diagnostics` is a stand-alone command line tool to create a diagnostic archive to help troubleshoot issues with ECK.
[float]
== Prepare

The tool is available at https://github.com/elastic/eck-diagnostics/. You can find detailed installation instructions there.



[float]
== Run

The eck-diagnostics tool supports various command line flags. Run it with `-h` or `--help` to print all available options. The only required flag is the `-r` or `--resources-namespace` flag to indicate the namespaces where your Elastic stack resources are deployed.
In addition there is also the `-o` or `--operator-namespaces` flag to allow you to indicate where the ECK operator is deployed. If you don't specify this flag the tool assumes the operator to be deplyed in the `elastic-system` namespace.

[source,bash]
----
eck-diagnostics -r <workload-namespaces> -o <operator-namespace>
----

By default the tool also automatically runs link:https://github.com/elastic/support-diagnostics[support diagnostics] for every Elasticsearch cluster and Kibana instance. This requires the temporary deployment of additional Pods into the Kubernetes cluster. If that is not desired, the feature can be turned off by specifying the `--run-stack-diagnostics=false` flag.


[float]
== Example


Assuming the ECK operator is deployed in a namespace called `operators` and Elastic stack resources are deployed in the  `security` and `monitoring` namespaces, you should run `eck-diagnostics` as follows:

[source,bash]
----
eck-diagnostics -o=operators -r=security,monitoring
----

Sample output:

[source,bash]
----
2021/10/06 20:34:20 ECK diagnostics with parameters: {DiagnosticImage:docker.elastic.co/eck-dev/support-diagnostics:8.1.4 ECKVersion: Kubeconfig: OperatorNamespaces:[operators] ResourcesNamespaces:[security monitoring] OutputDir:/tmp RunStackDiagnostics:true Verbose:false}
2021/10/06 20:34:22 Extracting Kubernetes diagnostics from operators
2021/10/06 20:34:23 ECK version is 1.8.0
2021/10/06 20:34:23 Extracting Kubernetes diagnostics from security
2021/10/06 20:34:23 Extracting Kubernetes diagnostics from monitoring
2021/10/06 20:34:24 ECK diagnostics written to /tmp/eck-diagnostic-2021-10-06T20-34-21.zip
----

