[id="{p}-kibana"]
== Running Kibana on ECK

The <<{p}-deploy-kibana,quickstart>> is a good starting point to quickly setup a Kibana instance with ECK.
The following sections describe how to customize a Kibana deployment to suit your requirements.

* <<{p}-kibana-eck-managed-es,Use an Elasticsearch cluster managed by ECK>>
* <<{p}-kibana-advanced-configuration,Advanced configuration>>
** <<{p}-kibana-pod-configuration,Pod Configuration>>
** <<{p}-kibana-configuration,Kibana Configuration>>
** <<{p}-kibana-scaling,Scaling out a Kibana deployment>>
* <<{p}-kibana-secure-settings,Secure settings>>
* <<{p}-kibana-http-configuration,HTTP Configuration>>
** <<{p}-kibana-http-publish,Load balancer settings and TLS SANs>>
** <<{p}-kibana-http-custom-tls,Provide your own certificate>>
** <<{p}-kibana-http-disable-tls,Disable TLS>>

[float]
[id="{p}-kibana-eck-managed-es"]
=== Use an Elasticsearch cluster managed by ECK

It is quite straightforward to connect a Kibana instance to an Elasticsearch cluster managed by ECK:

[source,yaml,subs="attributes"]
----
apiVersion: kibana.k8s.elastic.co/{eck_crd_version}
kind: Kibana
metadata:
  name: quickstart
spec:
  version: {version}
  count: 1
  elasticsearchRef:
    name: quickstart
    namespace: default
----

NOTE: `namespace` is optional if the Elasticsearch cluster is running in the same namespace as Kibana.

The Kibana configuration file is automatically setup by ECK to establish a secure connection to Elasticsearch.

[float]
[id="{p}-kibana-advanced-configuration"]
=== Advanced configuration

If you already have read the documentation about how to run Elasticsearch on ECK then most of the concepts and the ideas
described here will sound familiar to you.
This is because the resource definitions in ECK share the same philosophy when it comes to:

* Customizing the Pod configuration
* Customizing the product configuration
* Managing HTTP settings
* Using secure settings

[float]
[id="{p}-kibana-pod-configuration"]
==== Pod Configuration
You can define a <<{p}-pod-template,pod template>> to customize the Kibana pod and override any configuration values.

The following example demonstrates how to create a Kibana deployment with custom node affinity and resource limits.

[source,yaml,subs="attributes"]
----
apiVersion: kibana.k8s.elastic.co/{eck_crd_version}
kind: Kibana
metadata:
  name: kibana-sample
spec:
  version: {version}
  count: 1
  elasticsearchRef:
    name: "elasticsearch-sample"
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 1Gi
            cpu: 0.5
          limits:
            memory: 2Gi
            cpu: 2
      nodeSelector:
        type: frontend
----

NOTE: The name of the container in the pod template must be `kibana`.

See <<{p}-compute-resources-kibana-and-apm>> for more information.

[float]
[id="{p}-kibana-configuration"]
==== Kibana Configuration
You can add your own Kibana settings to the `spec.config` section.

The following example demonstrates how to set the `elasticsearch.requestHeadersWhitelist` configuration option:

[source,yaml,subs="attributes"]
----
apiVersion: kibana.k8s.elastic.co/{eck_crd_version}
kind: Kibana
metadata:
  name: kibana-sample
spec:
  version: {version}
  count: 1
  elasticsearchRef:
    name: "elasticsearch-sample"
  config:
     elasticsearch.requestHeadersWhitelist:
     - authorization
----

NOTE: The configuration items you provide always take precedence over the ones that are generated by the operator.

[float]
[id="{p}-kibana-scaling"]
=== Scale out a Kibana deployment

You may want to deploy more than one instance of Kibana.
In this case all the instances must share the same encryption key.

This can be done either directly in the `spec.config` section:

[source,yaml]
----
spec:
  config:
     xpack.security.encryptionKey: my-secret-key
----

Or by using a secure setting (recommended) as described in the next section.

[float]
[id="{p}-kibana-secure-settings"]
=== Secure Settings

<<{p}-es-secure-settings,Similar to Elasticsearch>>, you can use Kubernetes secrets to manage secure settings for Kibana as well.

For example, you can define a custom encryption key for Kibana as follows:

. Create a secret containing the desired setting:
+
[source,yaml,subs="attributes"]
----
kubectl create secret generic kibana-secret-settings \
 --from-literal=xpack.security.encryptionKey=94d2263b1ead716ae228277049f19975aff864fb4fcfe419c95123c1e90938cd
----
+
. Add a reference to the secret in the `secureSettings` section:
+
[source,yaml,subs="attributes"]
----
apiVersion: kibana.k8s.elastic.co/{eck_crd_version}
kind: Kibana
metadata:
  name: kibana-sample
spec:
  version: {version}
  count: 3
  elasticsearchRef:
    name: "elasticsearch-sample"
  secureSettings:
  - secretName: kibana-secret-settings
----

[float]
[id="{p}-kibana-http-configuration"]
=== HTTP Configuration

[float]
[id="{p}-kibana-http-publish"]
==== Load balancer settings and TLS SANs

By default a `ClusterIP` link:https://kubernetes.io/docs/concepts/services-networking/service/[service] is created and associated with the Kibana deployment.
You may want to expose Kibana externally with a link:https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer[load balancer].
In which case you may also want to include a custom DNS name or IP in the self-generated certificate.

[source,yaml,subs="attributes"]
----
apiVersion: kibana.k8s.elastic.co/{eck_crd_version}
kind: Kibana
metadata:
  name: kibana-sample
spec:
  version: {version}
  count: 1
  elasticsearchRef:
    name: "elasticsearch-sample"
  http:
    service:
      spec:
        type: LoadBalancer # default is ClusterIP
    tls:
      selfSignedCertificate:
        subjectAltNames:
        - ip: 1.2.3.4
        - dns: kibana.example.com
----

You can also use these two features separately, either expose the service or add some subjects to the
self-signed certificate.

[float]
[id="{p}-kibana-http-custom-tls"]
==== Provide your own certificate

If you want to use your own certificate, the required configuration is identical to Elasticsearch.  See: <<{p}-custom-http-certificate>>.

[float]
[id="{p}-kibana-http-disable-tls"]
==== Disable TLS

You can disable the generation of the self-signed certificate and hence disable TLS.

[source,yaml,subs="attributes"]
----
apiVersion: kibana.k8s.elastic.co/{eck_crd_version}
kind: Kibana
metadata:
  name: kibana-sample
spec:
  version: {version}
  count: 1
  elasticsearchRef:
    name: "elasticsearch-sample"
  http:
    tls:
      selfSignedCertificate:
        disabled: true
----
