:parent_page_id: logstash-specification
ifdef::env-github[]
****
link:https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-{page_id}.html[View this document on the Elastic website]
****
endif::[]

[id="{p}-logstash-update-strategy"]
= Update Strategy

The operator takes a Pod down to restart and applies a new configuration value. All Pods are restarted in reverse ordinal order.

== Default behavior

When `updateStrategy` is not present in the specification, it defaults to the following:

[source,yaml,subs="attributes,+macros,callouts"]
----
spec:
  updateStrategy:
    type: "RollingUpdate" <1>
    rollingUpdate:
      partition: 0        <2>
      maxUnavailable: 1   <3>
----

<1> The `RollingUpdate` strategy will update Pods one by one in reverse ordinal order.
<2> This means that all the Pods from ordinal Replicas-1 to `partition` are updated . You can split the update into partitions to perform link:https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#rolling-out-a-canary[canary rollout].
<3> This ensures that the cluster has no more than one unavailable Pod at any given point in time.

== OnDelete

[source,yaml]
----
spec:
  updateStrategy:
    type: "OnDelete"
----

`OnDelete` strategy does not automatically update Pods when a modification is made. You need to restart Pods yourself.
