:page_id: glossary
ifdef::env-github[]
****
link:https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-{page_id}.html[View this document on the Elastic website]
****
endif::[]
[id="{p}-{page_id}"]
= Glossary

This glossary supplements the link:https://kubernetes.io/docs/reference/glossary/[Kubernetes glossary] and covers terms used in the Elastic Cloud on Kubernetes (ECK) documentation.

[[CA]]CA::
  Certificate Authority. An entity that issues digital certificates to verify identities over a network.

[[Cluster]]Cluster::
  Can refer to either an link:https://www.elastic.co/guide/en/elasticsearch/reference/current/add-elasticsearch-nodes.html[Elasticsearch cluster] or a Kubernetes cluster depending on the context.

[[CRD]]CRD::
  link:https://kubernetes.io/docs/reference/glossary/?fundamental=true#term-CustomResourceDefinition[Custom Resource Definition]. ECK extends the Kubernetes API with CRDs to allow users to deploy and manage {eck_resources_list} resources just as they would do with built-in Kubernetes resources.

[[ECK]]ECK::
  Elastic Cloud on Kubernetes. Kubernetes operator to orchestrate {eck_resources_list} deployments on Kubernetes.

[[EKS]]EKS::
  link:https://aws.amazon.com/eks/[Elastic Kubernetes Service]. Managed Kubernetes service provided by Amazon Web Services (AWS).

[[GCS]]GCS::
  Google Cloud Storage. Block storage service provided by Google Cloud Platform (GCP).

[[GKE]]GKE::
  link:https://cloud.google.com/kubernetes-engine/[Google Kubernetes Engine]. Managed Kubernetes service provided by Google Cloud Platform (GCP).

[[k8s]]K8s::
  Shortened form (numeronym) of "Kubernetes" derived from replacing "ubernete" with "8".

[[Node]]Node::
  Can refer to either an link:https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html[Elasticsearch Node] or a link:https://kubernetes.io/docs/concepts/architecture/nodes/[Kubernetes Node] depending on the context. ECK maps an Elasticsearch node to a Kubernetes Pod which can get scheduled onto any available Kubernetes node that can satisfy the <<{p}-managing-compute-resources,resource requirements>> and link:https://kubernetes.io/docs/concepts/configuration/assign-pod-node/[node constraints] defined in the <<{p}-customize-pods,pod template>>.

[[NodeSet]]NodeSet::
  A set of Elasticsearch nodes that share the same Elasticsearch configuration and a Kubernetes Pod template. Multiple NodeSets can be defined in the Elasticsearch CRD to achieve a cluster topology consisting of groups of Elasticsearch nodes with different node roles, resource requirements and hardware configurations (Kubernetes node constraints).

[[OpenShift]]OpenShift::
  A Kubernetes link:https://www.openshift.com/[platform] by RedHat.

[[Operator]]Operator::
  A design pattern in Kubernetes for link:https://kubernetes.io/docs/concepts/extend-kubernetes/operator/[managing custom resources]. ECK implements the operator pattern to manage Elasticsearch, Kibana and APM Server resources on Kubernetes.

[[PDB]]PDB::
  link:https://kubernetes.io/docs/reference/glossary/?all=true#term-pod-disruption-budget[Pod Disruption Budget].

[[PVC]]PVC::
  link:https://kubernetes.io/docs/reference/glossary/?all=true#term-persistent-volume-claim[Persistent Volume Claim].

[[QoS]]QoS::
  Quality of Service. When a Kubernetes cluster is under heavy load, the Kubernetes scheduler makes pod eviction decisions based on the link:https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/[QoS class of individual pods]. <<{p}-managing-compute-resources>> explains how to define QoS classes for Elasticsearch, Kibana and APM Server pods.

[[RBAC]]RBAC::
  Role-based Access Control. A security mechanism in Kubernetes where access to cluster resources is restricted to principals having the appropriate role. Check https://kubernetes.io/docs/reference/access-authn-authz/rbac/ for more information.
